use_frameworks!

target 'collection-view-layouts_Example' do
    platform :ios, '8.0'

    pod 'collection-view-layouts/Core', :path => '../'
    pod 'collection-view-layouts/TagsLayout', :path => '../'
    pod 'collection-view-layouts/PinterestLayout', :path => '../'
    pod 'collection-view-layouts/Px500Layout', :path => '../'
    pod 'collection-view-layouts/InstagramLayout', :path => '../'
    pod 'collection-view-layouts/FlipboardLayout', :path => '../'
    pod 'collection-view-layouts/FacebookLayout', :path => '../'
    pod 'collection-view-layouts/FlickrLayout', :path => '../'

    target 'collection-view-layouts_Tests' do
        inherit! :search_paths
        
        pod 'Quick', '2.1.0'
        pod 'Nimble', '8.0.2'
    end
end
